export const ADD_TRANSLATION = 'ADD_TRANSLATION';
export const DELETE_TRANSLATION = 'DELETE_TRANSLATION';
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION';
export const ADD_TRANSLATIONS = 'ADD_TRANSLATIONS';

export const MARK_TRANSLATION_FOR_EDITING = 'MARK_TRANSLATION_FOR_EDITING';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_SCREEN_TYPE = 'SET_SCREEN_TYPE';
