export const ADD_TRANSLATION = 'ADD_TRANSLATION';
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION';
export const ADD_TRANSLATIONS = 'ADD_TRANSLATIONS';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
