export const EDIT_TRANSLATION_SCREEN = 'EDIT_TRANSLATION_SCREEN';
export const CREATE_TRANSLATION_SCREEN = 'CREATE_TRANSLATION_SCREEN';
export const USER_PROFILE_SCREEN = 'USER_PROFILE_SCREEN';
export const DICTIONARY_SCREEN = 'DICTIONARY_SCREEN';
